In [98]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy.linalg  

In [99]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [100]:
B = np.array([12, 0, 3])
np.linalg.solve(A, B)

array([16.06944444, -1.82638889, -0.13888889])